---
version: 2
updates:
    - allow:
          - dependency-type: all
      commit-message:
          include: scope
          prefix: chore
      directory: /
      open-pull-requests-limit: 10
      package-ecosystem: npm
      pull-request-branch-name:
          separator: /
      rebase-strategy: auto
      schedule:
          interval: daily
          time: "00:00"
          timezone: UTC
      versioning-strategy: auto
