---
include:
    -
        template: Security/SAST.gitlab-ci.yml

stages:
    - test
    - security

sast:
    stage: security

.test_script:
    script:
        - apk update
        - apk upgrade
        - apk add bash curl git nodejs
        - 'corepack enable && corepack prepare --activate pnpm@7.1.0'
        - pnpm config set store-dir .pnpm-store
        - .gitlab-ci/node_js.sh
        - .gitlab-ci/test.sh

'node:16':
    extends: .test_script
    image: 'node:16-alpine'
    stage: test
