---
include:
  - template: Security/SAST.gitlab-ci.yml

stages:
  - test

sast:
  stage: test

before_script:
  - whoami
  - apk update
  - apk upgrade
  - apk add bash curl git nodejs
  - 'curl -f https://get.pnpm.io/v6.14.js | node - add --global pnpm@6'
  - pnpm config set store-dir .pnpm-store
  - .gitlab-ci/node_js.sh

'node:12':
  image: 'node:12-alpine'
  stage: test
  script:
    - .gitlab-ci/test.sh

'node:14':
  image: 'node:14-alpine'
  stage: test
  script:
    - .gitlab-ci/test.sh

'node:16':
  image: 'node:16-alpine'
  stage: test
  script:
    - .gitlab-ci/test.sh
