image: "node:lts-alpine"

variables:
  CI_NAME: gitlab
  CI_EMAIL: gitlab-ci@example.com
  TEST_CMD_TEST: "$(git rev-parse HEAD)"

stages:
  - test
  - release

before_script:
  - ".gitlab-ci/node_js.sh"

test:
  stage: test

  script:
    - "env | sort"
#    - ".gitlab-ci/test.sh"

release:
  stage: release
  when: manual

  only:
    - master

  script:
    - ".gitlab-ci/release.sh"
