image: "node:lts-alpine"

stages:
  - test
  - release

before_script:
  - "apk update"
  - "apk upgrade"
  - "apk add bash"
  - ".gitlab-ci/node_js.sh"

test:
  stage: test

  script:
    - "echo \"${CI_COMMIT_SHA}\""
    - "echo \"$(git rev-parse HEAD)\""
    - "echo \"${CI_REPOSITORY_URL}\""
#    - ".gitlab-ci/test.sh"

release:
  stage: release
  when: manual

  only:
    - master

  script:
    - ".gitlab-ci/release.sh"
