---
image: 'node:lts-alpine'

stages:
  - verify

before_script:
  - 'apk update'
  - 'apk upgrade'
  - 'apk add bash git'
  - .gitlab-ci/node_js.sh

test:
  stage: verify

  script:
    - .gitlab-ci/test.sh
