image: "node:lts-alpine"

stages:
  - test
  - release

before_script:
  - "apk update"
  - "apk upgrade"
  - "apk add bash git"
  - ".gitlab-ci/node_js.sh"

test:
  stage: test

  script:
    - "git checkout -B \"${CI_COMMIT_REF_NAME}\" \"${CI_COMMIT_SHA}\""
    - "git status"
#    - ".gitlab-ci/test.sh"

release:
  stage: release
  when: manual

  only:
    - master

  script:
    - ".gitlab-ci/release.sh"
