variables:
  CI_NAME: gitlab
  CI_EMAIL: gitlab-ci@example.com

stages:
  - test
  - release

default:
  image: "node:lts-alpine"

  before_script:
    - ".gitlab-ci/node_js.sh"

test:
  stage: test

  except:
    variables:
      - "$GITLAB_USER_LOGIN == $CI_NAME"

  tags:
    - node

  script:
    - "env | sort"
    # - ".gitlab-ci/test.sh"

release:
  stage: release
  when: on_success

  except:
    variables:
      - "$GITLAB_USER_LOGIN == $CI_NAME"

  tags:
    - node

  only:
    - master

  script:
    - ".gitlab-ci/release.sh"
