cacheFolder: .yarn/cache

changesetBaseRefs:
    - master
    - origin/master
    - upstream/master
    - main
    - origin/main
    - upstream/main

checksumBehavior: throw

cloneConcurrency: 2

compressionLevel: mixed

defaultLanguageName: node

defaultProtocol: "npm:"

defaultSemverRangePrefix: ^

enableGlobalCache: false

enableMessageNames: true

enableMirror: true

enableStrictSettings: true

enableStrictSsl: true

enableTelemetry: false

enableTimers: true

enableTransparentWorkspaces: true

httpRetry: 3

httpTimeout: 60000

ignoreCwd: true

ignorePath: false

installStatePath: .yarn/install-state.gz

lockfileFilename: yarn.lock

networkConcurrency: 50

nmHoistingLimits: none

nmMode: hardlinks-local

nmSelfReferences: true

nodeLinker: node-modules

npmAlwaysAuth: false

npmRegistryServer: "https://registry.yarnpkg.com"

patchFolder: .yarn/patches

plugins:
    - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
      spec: "@yarnpkg/plugin-interactive-tools"

pnpDataPath: .pnp.data.json

pnpEnableInlining: true

pnpFallbackMode: dependencies-only

pnpMode: strict

pnpShebang: "#!/usr/bin/env node"

pnpUnpluggedFolder: .yarn/unplugged

preferAggregateCacheInfo: false

preferInteractive: true

preferTruncatedLines: false

supportedArchitectures:
    os:
        - linux

telemetryInterval: 7

virtualFolder: .yarn/__virtual__

yarnPath: .yarn/releases/yarn-3.2.1.cjs
