module.exports = {
  // addTrailingCommas: false,
  // arrowParens: 'always',
  // braceStyle: 'psr-2',
  // bracketSpacing: true,
  // endOfLine: 'lf',
  // htmlWhitespaceSensitivity: 'css',
  // inlineConditionals: true,
  // inlineLoops: true,
  // insertPragma: false,
  // jsxBracketSameLine: false,
  // jsxSingleQuote: false,
  phpVersion: '7.4',
  // preferHashLabels: true,
  preferSingleQuotes: false,
  // printWidth: 80,
  // proseWrap: 'preserve',
  // quoteProps: 'as-needed',
  // requirePragma: false,
  // semi: true,
  singleQuote: true,
  // tabWidth: 2,
  trailingComma: 'all',
  // trailingCommaPHP: true,
  // useTabs: false,
  // vueIndentScriptAndStyle: false,
  // xmlSelfClosingSpace: true,
  // xmlWhitespaceSensitivity: 'strict',
  overrides: [
    {
      files: [
        '*.aw',
        '*.ctp',
        '*.fcgi',
        '*.inc',
        '*.php',
        '*.php3',
        '*.php4',
        '*.php5',
        '*.phps',
        '*.phpt',
        '*.phtml',
        '.php_cs',
        '.php_cs.dist',
        'artisan',
        'Phakefile',
      ],
      options: {
        singleQuote: false,
        // tabWidth: 4,
      },
    },
    {
      files: ['.simplecov'],
      options: {
        parser: 'ruby',
      },
    },
  ],
};
