'use strict';

const { override, typescriptOverride } = require(`./lib/helpers.cjs`);

/** @typedef {import('eslint').BaseConfig} */

/** @type {BaseConfig} */
module.exports = {
	extends: [require.resolve(`./browser.cjs`)],
	overrides: [
		override([`?(c)js`], {
			rules: {
				'@typescript-eslint/no-var-requires': `off`,
			},
		}),
		typescriptOverride({
			rules: {
				'no-unused-vars': `off`,

				// eslint-disable-next-line sort-keys
				'@typescript-eslint/explicit-function-return-type': `off`,
			},
		}),
		override([{ files: [`shims-tsx.d.ts`] }], {
			rules: {
				'@typescript-eslint/no-empty-interface': `off`,
				'@typescript-eslint/no-explicit-any': `off`,
				'@typescript-eslint/no-unused-vars': `off`,
			},
		}),
	],
	parser: require.resolve(`vue-eslint-parser`),
	parserOptions: {
		extraFileExtensions: [`.vue`],
		parser: require.resolve(`@typescript-eslint/parser`),
	},
	plugins: [`vue`],
	rules: {
		'vue/array-bracket-newline': `off`,
		'vue/array-bracket-spacing': `off`,
		'vue/arrow-spacing': `off`,
		'vue/attribute-hyphenation': `error`,
		'vue/attributes-order': `error`,
		'vue/block-lang': 0,
		'vue/block-spacing': `off`,
		'vue/block-tag-newline': `off`,
		'vue/brace-style': `off`,
		'vue/camelcase': 0,
		'vue/comma-dangle': `off`,
		'vue/comma-spacing': `off`,
		'vue/comma-style': `off`,
		'vue/comment-directive': `error`,
		'vue/component-api-style': 0,
		'vue/component-definition-name-casing': `error`,
		'vue/component-name-in-template-casing': 0,
		'vue/component-options-name-casing': 0,
		'vue/component-tags-order': `error`,
		'vue/custom-event-name-casing': 0,
		'vue/define-macros-order': 0,
		'vue/dot-location': `off`,
		'vue/dot-notation': 0,
		'vue/eqeqeq': 0,
		'vue/first-attribute-linebreak': `error`,
		'vue/func-call-spacing': `off`,
		'vue/html-button-has-type': 0,
		'vue/html-closing-bracket-newline': `off`,
		'vue/html-closing-bracket-spacing': `off`,
		'vue/html-comment-content-newline': 0,
		'vue/html-comment-content-spacing': 0,
		'vue/html-comment-indent': 0,
		'vue/html-end-tags': `off`,
		'vue/html-indent': `off`,
		'vue/html-quotes': `off`,
		'vue/html-self-closing': [
			`error`,
			{
				html: {
					void: `any`,
				},
			},
		],
		'vue/jsx-uses-vars': `error`,
		'vue/key-spacing': `off`,
		'vue/keyword-spacing': `off`,
		'vue/match-component-file-name': 0,
		'vue/match-component-import-name': 0,
		'vue/max-attributes-per-line': `off`,
		'vue/max-len': `off`,
		'vue/multi-word-component-names': `error`,
		'vue/multiline-html-element-content-newline': `off`,
		'vue/mustache-interpolation-spacing': `off`,
		'vue/new-line-between-multi-line-property': 0,
		'vue/next-tick-style': 0,
		'vue/no-arrow-functions-in-watch': `error`,
		'vue/no-async-in-computed-properties': `error`,
		'vue/no-bare-strings-in-template': 0,
		'vue/no-boolean-default': 0,
		'vue/no-child-content': `error`,
		'vue/no-computed-properties-in-data': `error`,
		'vue/no-constant-condition': 0,
		'vue/no-custom-modifiers-on-v-model': 0,
		'vue/no-deprecated-data-object-declaration': `error`,
		'vue/no-deprecated-destroyed-lifecycle': `error`,
		'vue/no-deprecated-dollar-listeners-api': `error`,
		'vue/no-deprecated-dollar-scopedslots-api': `error`,
		'vue/no-deprecated-events-api': `error`,
		'vue/no-deprecated-filter': `error`,
		'vue/no-deprecated-functional-template': `error`,
		'vue/no-deprecated-html-element-is': `error`,
		'vue/no-deprecated-inline-template': `error`,
		'vue/no-deprecated-props-default-this': `error`,
		'vue/no-deprecated-router-link-tag-prop': `error`,
		'vue/no-deprecated-scope-attribute': `error`,
		'vue/no-deprecated-slot-attribute': `error`,
		'vue/no-deprecated-slot-scope-attribute': `error`,
		'vue/no-deprecated-v-bind-sync': `error`,
		'vue/no-deprecated-v-is': `error`,
		'vue/no-deprecated-v-on-native-modifier': `error`,
		'vue/no-deprecated-v-on-number-modifiers': `error`,
		'vue/no-deprecated-vue-config-keycodes': `error`,
		'vue/no-dupe-keys': `error`,
		'vue/no-dupe-v-else-if': `error`,
		'vue/no-duplicate-attr-inheritance': 0,
		'vue/no-duplicate-attributes': `error`,
		'vue/no-empty-component-block': 0,
		'vue/no-empty-pattern': 0,
		'vue/no-export-in-script-setup': `error`,
		'vue/no-expose-after-await': `error`,
		'vue/no-extra-parens': `off`,
		'vue/no-irregular-whitespace': 0,
		'vue/no-lifecycle-after-await': `error`,
		'vue/no-lone-template': `error`,
		'vue/no-loss-of-precision': 0,
		'vue/no-multi-spaces': `off`,
		'vue/no-multiple-objects-in-class': 0,
		'vue/no-multiple-slot-args': `error`,
		'vue/no-multiple-template-root': 0,
		'vue/no-mutating-props': `error`,
		'vue/no-parsing-error': `error`,
		'vue/no-potential-component-option-typo': 0,
		'vue/no-ref-as-operand': `error`,
		'vue/no-reserved-component-names': `error`,
		'vue/no-reserved-keys': `error`,
		'vue/no-reserved-props': `error`,
		'vue/no-restricted-block': 0,
		'vue/no-restricted-call-after-await': 0,
		'vue/no-restricted-class': 0,
		'vue/no-restricted-component-options': 0,
		'vue/no-restricted-custom-event': 0,
		'vue/no-restricted-html-elements': 0,
		'vue/no-restricted-props': 0,
		'vue/no-restricted-static-attribute': 0,
		'vue/no-restricted-syntax': 0,
		'vue/no-restricted-v-bind': 0,
		'vue/no-setup-props-destructure': `error`,
		'vue/no-shared-component-data': `error`,
		'vue/no-side-effects-in-computed-properties': `error`,
		'vue/no-spaces-around-equal-signs-in-attribute': `off`,
		'vue/no-sparse-arrays': 0,
		'vue/no-static-inline-styles': 0,
		'vue/no-template-key': `error`,
		'vue/no-template-shadow': `error`,
		'vue/no-template-target-blank': 0,
		'vue/no-textarea-mustache': `error`,
		'vue/no-this-in-before-route-enter': 0,
		'vue/no-undef-components': 0,
		'vue/no-undef-properties': 0,
		'vue/no-unsupported-features': 0,
		'vue/no-unused-components': `error`,
		'vue/no-unused-properties': 0,
		'vue/no-unused-refs': 0,
		'vue/no-unused-vars': `error`,
		'vue/no-use-computed-property-like-method': `error`,
		'vue/no-use-v-if-with-v-for': `error`,
		'vue/no-useless-concat': 0,
		'vue/no-useless-mustaches': 0,
		'vue/no-useless-template-attributes': `error`,
		'vue/no-useless-v-bind': 0,
		'vue/no-v-for-template-key': 0,
		'vue/no-v-for-template-key-on-child': `error`,
		'vue/no-v-html': `error`,
		'vue/no-v-model-argument': 0,
		'vue/no-v-text': 0,
		'vue/no-v-text-v-html-on-component': `error`,
		'vue/no-watch-after-await': `error`,
		'vue/object-curly-newline': `off`,
		'vue/object-curly-spacing': `off`,
		'vue/object-property-newline': `off`,
		'vue/object-shorthand': 0,
		'vue/one-component-per-file': `error`,
		'vue/operator-linebreak': `off`,
		'vue/order-in-components': `error`,
		'vue/padding-line-between-blocks': 0,
		'vue/prefer-import-from-vue': `error`,
		'vue/prefer-prop-type-boolean-first': 0,
		'vue/prefer-separate-static-class': 0,
		'vue/prefer-template': 0,
		'vue/prefer-true-attribute-shorthand': 0,
		'vue/prop-name-casing': `error`,
		'vue/quote-props': `off`,
		'vue/require-component-is': `error`,
		'vue/require-default-prop': `error`,
		'vue/require-direct-export': 0,
		'vue/require-emit-validator': 0,
		'vue/require-explicit-emits': `error`,
		'vue/require-expose': 0,
		'vue/require-name-property': 0,
		'vue/require-prop-type-constructor': `error`,
		'vue/require-prop-types': `error`,
		'vue/require-render-return': `error`,
		'vue/require-slots-as-functions': `error`,
		'vue/require-toggle-inside-transition': `error`,
		'vue/require-v-for-key': `error`,
		'vue/require-valid-default-prop': `error`,
		'vue/return-in-computed-property': `error`,
		'vue/return-in-emits-validator': `error`,
		'vue/script-indent': `off`,
		'vue/singleline-html-element-content-newline': `off`,
		'vue/sort-keys': 0,
		'vue/space-in-parens': `off`,
		'vue/space-infix-ops': `off`,
		'vue/space-unary-ops': `off`,
		'vue/static-class-names-order': 0,
		'vue/template-curly-spacing': `off`,
		'vue/this-in-template': `error`,
		'vue/use-v-on-exact': `error`,
		'vue/v-bind-style': `error`,
		'vue/v-for-delimiter-style': 0,
		'vue/v-on-event-hyphenation': `error`,
		'vue/v-on-function-call': 0,
		'vue/v-on-style': `error`,
		'vue/v-slot-style': `error`,
		'vue/valid-attribute-name': `error`,
		'vue/valid-define-emits': `error`,
		'vue/valid-define-props': `error`,
		'vue/valid-model-definition': 0,
		'vue/valid-next-tick': `error`,
		'vue/valid-template-root': `error`,
		'vue/valid-v-bind': `error`,
		'vue/valid-v-bind-sync': 0,
		'vue/valid-v-cloak': `error`,
		'vue/valid-v-else': `error`,
		'vue/valid-v-else-if': `error`,
		'vue/valid-v-for': `error`,
		'vue/valid-v-html': `error`,
		'vue/valid-v-if': `error`,
		'vue/valid-v-is': `error`,
		'vue/valid-v-memo': `error`,
		'vue/valid-v-model': `error`,
		'vue/valid-v-on': `error`,
		'vue/valid-v-once': `error`,
		'vue/valid-v-pre': `error`,
		'vue/valid-v-show': `error`,
		'vue/valid-v-slot': `error`,
		'vue/valid-v-text': `error`,
	},
};
