'use strict';

/** @typedef {import('eslint').BaseConfig} */

/** @type {BaseConfig} */
module.exports = {
  env: {
    'jest/globals': true,
  },
  plugins: ['jest'],
  rules: {
    'jest/consistent-test-it': 0,
    'jest/expect-expect': 'error',
    'jest/lowercase-name': 0,
    'jest/max-nested-describe': 0,
    'jest/no-alias-methods': 0,
    'jest/no-commented-out-tests': 'error',
    'jest/no-conditional-expect': 'error',
    'jest/no-deprecated-functions': 'error',
    'jest/no-disabled-tests': 'error',
    'jest/no-done-callback': 'error',
    'jest/no-duplicate-hooks': 0,
    'jest/no-export': 'error',
    'jest/no-focused-tests': 'error',
    'jest/no-hooks': 0,
    'jest/no-identical-title': 'error',
    'jest/no-if': 0,
    'jest/no-interpolation-in-snapshots': 'error',
    'jest/no-jasmine-globals': 'error',
    'jest/no-jest-import': 'error',
    'jest/no-large-snapshots': 0,
    'jest/no-mocks-import': 'error',
    'jest/no-restricted-matchers': 0,
    'jest/no-standalone-expect': 'error',
    'jest/no-test-prefixes': 'error',
    'jest/no-test-return-statement': 0,
    'jest/prefer-called-with': 0,
    'jest/prefer-expect-assertions': 0,
    'jest/prefer-expect-resolves': 0,
    'jest/prefer-hooks-on-top': 0,
    'jest/prefer-lowercase-title': 0,
    'jest/prefer-spy-on': 0,
    'jest/prefer-strict-equal': 0,
    'jest/prefer-to-be': 0,
    'jest/prefer-to-be-null': 0,
    'jest/prefer-to-be-undefined': 0,
    'jest/prefer-to-contain': 0,
    'jest/prefer-to-have-length': 0,
    'jest/prefer-todo': 0,
    'jest/require-hook': 0,
    'jest/require-to-throw-message': 0,
    'jest/require-top-level-describe': 0,
    'jest/unbound-method': 0,
    'jest/valid-describe-callback': 0,
    'jest/valid-expect': 'error',
    'jest/valid-expect-in-promise': 'error',
    'jest/valid-title': 'error',
  },
};
