'use strict';

/** @typedef {import('eslint').BaseConfig} */

/** @type {BaseConfig} */
module.exports = {
	extends: ['plugin:vue/vue3-recommended'],
	parserOptions: {
		ecmaVersion: 'latest',
	},
	rules: {
		'vue/attribute-hyphenation': 'error',
		'vue/attributes-order': 'error',
		'vue/block-lang': 0,
		'vue/camelcase': 0,
		'vue/component-api-style': 0,
		'vue/component-definition-name-casing': 'error',
		'vue/component-name-in-template-casing': 0,
		'vue/component-options-name-casing': 0,
		'vue/component-tags-order': 'error',
		'vue/custom-event-name-casing': 0,
		'vue/define-macros-order': 0,
		'vue/dot-notation': 0,
		'vue/eqeqeq': 0,
		'vue/first-attribute-linebreak': 'error',
		'vue/html-button-has-type': 0,
		'vue/html-comment-content-newline': 0,
		'vue/html-comment-content-spacing': 0,
		'vue/html-comment-indent': 0,
		'vue/html-self-closing': [
			'error',
			{
				html: {
					void: 'any',
				},
			},
		],
		'vue/match-component-file-name': 0,
		'vue/match-component-import-name': 0,
		'vue/max-len': 'off',
		'vue/new-line-between-multi-line-property': 0,
		'vue/next-tick-style': 0,
		'vue/no-bare-strings-in-template': 0,
		'vue/no-boolean-default': 0,
		'vue/no-constant-condition': 0,
		'vue/no-custom-modifiers-on-v-model': 0,
		'vue/no-duplicate-attr-inheritance': 0,
		'vue/no-empty-component-block': 0,
		'vue/no-empty-pattern': 0,
		'vue/no-irregular-whitespace': 0,
		'vue/no-lone-template': 'error',
		'vue/no-loss-of-precision': 0,
		'vue/no-multiple-objects-in-class': 0,
		'vue/no-multiple-slot-args': 'error',
		'vue/no-multiple-template-root': 0,
		'vue/no-potential-component-option-typo': 0,
		'vue/no-restricted-block': 0,
		'vue/no-restricted-call-after-await': 0,
		'vue/no-restricted-class': 0,
		'vue/no-restricted-component-options': 0,
		'vue/no-restricted-custom-event': 0,
		'vue/no-restricted-html-elements': 0,
		'vue/no-restricted-props': 0,
		'vue/no-restricted-static-attribute': 0,
		'vue/no-restricted-syntax': 0,
		'vue/no-restricted-v-bind': 0,
		'vue/no-sparse-arrays': 0,
		'vue/no-static-inline-styles': 0,
		'vue/no-template-shadow': 'error',
		'vue/no-template-target-blank': 0,
		'vue/no-this-in-before-route-enter': 0,
		'vue/no-undef-components': 0,
		'vue/no-undef-properties': 0,
		'vue/no-unsupported-features': 0,
		'vue/no-unused-properties': 0,
		'vue/no-unused-refs': 0,
		'vue/no-useless-concat': 0,
		'vue/no-useless-mustaches': 0,
		'vue/no-useless-v-bind': 0,
		'vue/no-v-for-template-key': 0,
		'vue/no-v-html': 'error',
		'vue/no-v-model-argument': 0,
		'vue/no-v-text': 0,
		'vue/object-shorthand': 0,
		'vue/one-component-per-file': 'error',
		'vue/order-in-components': 'error',
		'vue/padding-line-between-blocks': 0,
		'vue/prefer-prop-type-boolean-first': 0,
		'vue/prefer-separate-static-class': 0,
		'vue/prefer-template': 0,
		'vue/prefer-true-attribute-shorthand': 0,
		'vue/prop-name-casing': 'error',
		'vue/require-default-prop': 'error',
		'vue/require-direct-export': 0,
		'vue/require-emit-validator': 0,
		'vue/require-explicit-emits': 'error',
		'vue/require-expose': 0,
		'vue/require-name-property': 0,
		'vue/require-prop-types': 'error',
		'vue/sort-keys': 0,
		'vue/static-class-names-order': 0,
		'vue/this-in-template': 'error',
		'vue/v-bind-style': 'error',
		'vue/v-for-delimiter-style': 0,
		'vue/v-on-event-hyphenation': 'error',
		'vue/v-on-function-call': 0,
		'vue/v-on-style': 'error',
		'vue/v-slot-style': 'error',
		'vue/valid-model-definition': 0,
		'vue/valid-v-bind-sync': 0,
	},
};
