---
name: CI
on:
    pull_request:
        types:
            - opened
            - reopened
            - synchronize
    push:
        branches:
            - main
    workflow_dispatch: {}
jobs:
    test:
        name: "Node.js ${{ matrix.node-version }}"
        runs-on: ubuntu-latest
        steps:
            - name: "Checkout Code"
              uses: actions/checkout@v3
            - name: "Setup Node"
              uses: actions/setup-node@v2
              with:
                  node-version: "${{ matrix.node-version }}"
            - name: "Install Dependencies"
              run: "yarn install --check-cache --immutable --immutable-cache"
            - name: "Test Code"
              run: "yarn test"
        strategy:
            fail-fast: false
            matrix:
                node-version:
                    - 16
                    - 18
